name: CI - Tests complets

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  backend:
    name: Backend - Tests Spring
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Run backend tests
        working-directory: Backend/tp_automatisation_tests
        run: mvn clean test

  frontend:
    name: Frontend - Tests Angular
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install & test frontend
        working-directory: Frontend/tp_automatisation_tests
        run: |
          npm install
          npm test -- --watch=false --browsers=ChromeHeadless

  selenium:
    name: Selenium - Tests E2E
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Run Selenium tests
        working-directory: selenium-tests
        run: mvn clean test

